name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests suite

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Tests
      run: |
        echo "-------- FSI --------"
        dotnet fsi test.fsx
        echo "-------- PROJECT (Standard) --------"
        dotnet run --project Standard
        echo "-------- PROJECT (ManagePackageVersionsCentrally) --------"
        dotnet run --project ManagePackageVersionsCentrally
